Repository hashicorp/packer-plugin-azure, pull requests merged in 2024-02, with the labels that each got.

#368 builder: don't log requests/responses by default
  .web-docs/README.md
  builder/azure/arm/inspector.go
  builder/azure/common/env.go
  builder/azure/dtl/inspector.go
  docs/README.md
Labels: enhancement

#375 builder: remove unused testUi function
  builder/azure/arm/builder_acc_test.go
Labels: tech-debt

#371 [HPR-1606] Add support specifying disk encryption set keys across replicated regions
  .web-docs/components/builder/arm/README.md
  builder/azure/arm/builder.go
  builder/azure/arm/config.go
  builder/azure/arm/config.hcl2spec.go
  builder/azure/arm/config_test.go
  builder/azure/arm/step_publish_to_shared_image_gallery.go
  builder/azure/arm/step_publish_to_shared_image_gallery_test.go
  builder/azure/common/constants/stateBag.go
  docs-partials/builder/azure/arm/Config-not-required.mdx
  docs-partials/builder/azure/arm/SharedImageGalleryDestination-not-required.mdx
  docs-partials/builder/azure/arm/TargetRegion-not-required.mdx
  docs-partials/builder/azure/arm/TargetRegion-required.mdx
  docs-partials/builder/azure/arm/TargetRegion.mdx
Labels: enhancement

#379 Fix regression in replicated_regions attribute
  builder/azure/arm/step_publish_to_shared_image_gallery.go
  builder/azure/arm/step_publish_to_shared_image_gallery_test.go
Labels: bug, regression

#381 Add default build location when no target region is set
  builder/azure/arm/builder.go
Labels: bug, enhancement

#382 typo: Change attatched to attached.
  builder/azure/arm/step_deploy_template.go
Labels: tech-debt

#383 Update validation check for Shallow Replication
  builder/azure/arm/config.go
Labels: bug, regression
